name: Convert documents to PDF/HTML

on:
  push:
    branches:
      - main
    paths:
      - '**.md'
      - '**.json'
      - '.github/workflows/doc_generation.yml'
      - '.github/requirements.txt'
      # Ignore Markdown files in the root
      - '!*.md'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch:
    name: Generate documents
    runs-on: ubuntu-latest
    steps:
      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install -y git libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0 fonts-wqy-microhei

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r .github/requirements.txt

      - name: Run generation script
        run: |
          # Set arbitrary EPOCH date to get reproducible PDF generation.
          # https://github.com/Kozea/WeasyPrint/issues/1553
          export SOURCE_DATE_EPOCH=1658210455
          python .github/scripts/convert_documents.py

      - name: Set up git credentials
        run : |
          git config --global user.email 'MozmarRobot@users.noreply.github.com'
          git config --global user.name 'MozMEAO Bot'

      - name: Commit changes to doc_updates branch
        continue-on-error: true
        run: |
          # Commit changes. Failure is allowed if there is nothing to commit.
          git checkout -B doc_updates
          git add .
          git commit -m "Convert documents"
          git push -f origin doc_updates

      - name: Open pull request
        continue-on-error: true
        run: |
          # continue-on-error is needed in case there is already an open PR
          changes=$(git diff --name-only main doc_updates -- | wc -l | awk '{print $1}')
          if [[ "$changes" = "0" ]];
          then
            echo "No changes."
          else
            # Create pull request
            gh pr create \
              --title "[pdf] Update converted documents" \
              --body "Convert documents to PDF/HTML" \
              --head doc_updates \
              --base main \
              --label l10n \
              --reviewer @mozilla/legal-l10n
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.L10N_LEGAL }}
